import { GetStaticProps } from 'next';
import Head from 'next/head';
import { CardPost } from '../components/CardPost';
import { ContainerHome, ContainerPosts } from '../styles/home';
import { getPrismicClient } from './api/services/prismic';
import Prismic from '@prismicio/client';
import { RichText } from 'prismic-dom';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';

interface Post {
  slug: string;
  title: string;
  excerpt: string;
  updateAt: string;
  author: string;
}

interface PostsProps {
  posts: Post[];
}

export default function Home({ posts }: PostsProps) {
  return (
    <ContainerHome>
      <Head>
        <title>Spacetraveling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContainerPosts>
        {posts.map((post) => (
          <CardPost key={post.slug} {...post} />
        ))}
      </ContainerPosts>
    </ContainerHome>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const prismic = getPrismicClient();

  const response = await prismic.query(
    [Prismic.predicates.at('document.type', 'post')],
    {
      fetch: ['post.title', 'post.content', 'post.author'],
      pageSize: 100,
    },
  );

  console.log(JSON.stringify(response, null, 2));
  const posts = response.results.map((post) => ({
    slug: post.uid,
    title: RichText.asText(post.data.title),
    excerpt:
      post.data.content.find((content) => content.type === 'paragraph')?.text ??
      '',
    updateAt: format(new Date(post.last_publication_date), 'dd MMM yyyy', {
      locale: ptBR,
    }),
    author: post.data.author,
  }));
  return {
    props: {
      posts,
    },
  };
};
